---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: hubot
    driver_config:
      box: centos-6.4
      box_url: http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130731.box

suites:
  - name: default
    run_list:
      - recipe[hubot::default]
    attributes:
