---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: hubot
    driver_config:
      box: CentOS 6.4

suites:
  - name: default
    run_list:
      - recipe[hubot::default]
    attributes:
